# Forward Mode Code Demo

In [102]:
import numpy as np
import pandas as pd
from AutoDiff import Ad_Var
from mpl_toolkits.mplot3d import Axes3D
%matplotlib widget
import matplotlib.pyplot as plt

## 1. Scalar function of one variable

$$ f = sin^2(2x) $$
Want to calculate the derivative of x at $\frac{\pi}{6}$

In [20]:
x = Ad_Var(np.pi/6)
f = (Ad_Var.sin(2*x))**2
print('Value: ',f.get_val())
print('Derivative: ', f.get_ders())

Value:  0.7499999999999999
Derivative:  1.7320508075688776


In [21]:
print(f)

Value = 0.7499999999999999
Derivative = 1.7320508075688776


## 2. Scalar function of multiple variables

$$ f = sin^2(2x) + z^y $$
Want to calculate the derivative of x at 1, y at 2, z at 3

In [22]:
x = Ad_Var(1, np.array([1, 0, 0]))
y = Ad_Var(2, np.array([0, 1, 0]))
z = Ad_Var(3, np.array([0, 0, 1]))
f = (Ad_Var.sin(2*x))**2 + z**y

print('Value: ',f.get_val())
print('Gradient: ', f.get_ders())

Value:  9.826821810431806
Gradient:  [-1.51360499  9.8875106   6.        ]


In [23]:
print(f)

Value = 9.826821810431806
Gradient = [-1.51360499  9.8875106   6.        ]


## 3. Vector function of multiple variables 

$$ f = \begin{bmatrix}sin^2(2x) + z^y\\
                e^x + z
        \end{bmatrix}$$ 
Want to calculate the derivative of x at 1, y at 2, z at 3

In [24]:
x = Ad_Var(1, np.array([1, 0, 0]))
y = Ad_Var(2, np.array([0, 1, 0]))
z = Ad_Var(3, np.array([0, 0, 1]))

f = np.array([(Ad_Var.sin(2*x))**2 + z**y, Ad_Var.exp(x) + z])
print('Value: ',Ad_Var.get_values(f))
print('Gradient: ', Ad_Var.get_jacobian(f,2,3)) # get_jacobian(functions_array, functions_dim, vars_dim)

Value:  [9.82682181 5.71828183]
Gradient:  [[-1.51360499  9.8875106   6.        ]
 [ 2.71828183  0.          1.        ]]


In [28]:
print(f)

[Value = 9.826821810431806
Gradient = [-1.51360499  9.8875106   6.        ]
 Value = 5.718281828459045
Gradient = [2.71828183 0.         1.        ]]


## 4. Function of variables with multiple input

$$ f = \begin{bmatrix}sin^2(2x) + z^y\\
                e^x + z
        \end{bmatrix}$$ 
Want to calculate the derivative of x at [1,2] , y at [2,3], z at 4 

In [30]:
x = Ad_Var(ders = np.array([1, 0, 0]))
y = Ad_Var(ders = np.array([0, 1, 0]))
z = Ad_Var(ders = np.array([0, 0, 1]))

f_string = "[(Ad_Var.sin(2*x))**2 + z**y, Ad_Var.exp(x) + z]"
Ad_Var.grid_eval(f_string, ['x', 'y', 'z'], [x, y, z], [[1, 2], [2,3], [4]])

{(1, 2, 4): (array([16.82682181,  6.71828183]),
  array([[-1.51360499, 22.18070978,  8.        ],
         [ 2.71828183,  0.        ,  1.        ]])),
 (1, 3, 4): (array([64.82682181,  6.71828183]),
  array([[-1.51360499, 88.72283911, 48.        ],
         [ 2.71828183,  0.        ,  1.        ]])),
 (2, 2, 4): (array([16.57275002, 11.3890561 ]),
  array([[ 1.97871649, 22.18070978,  8.        ],
         [ 7.3890561 ,  0.        ,  1.        ]])),
 (2, 3, 4): (array([64.57275002, 11.3890561 ]),
  array([[ 1.97871649, 88.72283911, 48.        ],
         [ 7.3890561 ,  0.        ,  1.        ]]))}

In [173]:
x = Ad_Var(ders = np.array([1, 0]))
y = Ad_Var(ders = np.array([0, 1]))
n = 100
f_string = "Ad_Var.cos(x)*Ad_Var.sin(y) - x**2/5 "
result = Ad_Var.grid_eval(f_string, ['x', 'y'], [x, y], [np.linspace(-5,5,n), np.linspace(-5,5,n)])

In [174]:
xx = np.zeros(n**2)
yy = np.zeros(n**2)
f_values = np.zeros(n**2)
f_der_x = np.zeros(n**2)
f_der_y = np.zeros(n**2)
for i in range(n**2):
    xx[i] = list(result.keys())[i][0]
    yy[i] = list(result.keys())[i][1]
    f_values[i] = list(result.values())[i][0]
    f_der_x[i] = list(result.values())[i][1][0]
    f_der_y[i] = list(result.values())[i][1][1]   


In [175]:
ax = Axes3D(plt.figure(figsize=(12, 8)))
ax = plt.axes(projection='3d')
ax.plot_surface(xx.reshape(-n,n), yy.reshape(-n,n), f_values.reshape(-n,n), alpha=0.5, cmap='viridis')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('f')
ax.set_proj_type('ortho')
plt.title('f = cos(x)*sin(y) - x**2/5 Function Value')
plt.show()

/Users/ivywang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [176]:
ax = Axes3D(plt.figure(figsize=(12, 8)))
ax = plt.axes(projection='3d')
ax.plot_surface(xx.reshape(-n,n), yy.reshape(-n,n), f_der_x.reshape(-n,n), alpha=0.5, cmap='viridis')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('f')
ax.set_proj_type('ortho')
plt.title('f = cos(x)*sin(y) - x**2/5 Partial Derivative of x')
plt.show()

/Users/ivywang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [177]:
ax = Axes3D(plt.figure(figsize=(12, 8)))
ax = plt.axes(projection='3d')
ax.plot_surface(xx.reshape(-n,n), yy.reshape(-n,n), f_der_y.reshape(-n,n), alpha=0.5, cmap='viridis')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('f')
ax.set_proj_type('ortho')
plt.title('f = cos(x)*sin(y) - x**2/5 Partial Derivative of y')
plt.show()

/Users/ivywang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …